
jenkins:
  systemMessage: "Jenkins configurado automáticamente con JCasC"
  security:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
  clouds:
    - docker:
        name: "docker-cloud"
        dockerApi:
          dockerHost:
            uri: "unix:///var/run/docker.sock"
        templates:
          - labelString: "maven"
            dockerTemplateBase:
              image: "maven:3.9-eclipse-temurin-17"
            remoteFs: "/home/jenkins/agent"
          - labelString: "terraform"
            dockerTemplateBase:
              image: "hashicorp/terraform:1.7"
            remoteFs: "/home/jenkins/agent"
jobs:
  - script: >
      pipelineJob('timbatumbao-ci-cd') {
        description('Pipeline de CI/CD para el proyecto Timbatumbao.')
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/AndyFM806/TIMBATUMBAOINFRA.git')
                }
                branch('main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
