jenkins:
  systemMessage: "Jenkins configurado con acceso directo admin/admin"

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  disableRememberMe: false

  clouds:
    - docker:
        name: "dind-cloud"
        dockerApi:
          dockerHost:
            uri: "tcp://docker-dind:2375"   # con tu docker-compose esto está OK

        templates:

          # --- Agente para etapas Docker ---
          - name: "docker-agent"
            labelString: "docker"
            remoteFs: "/home/jenkins"
            instanceCapStr: "5"
            dockerTemplateBase:
              image: "jenkins/inbound-agent:alpine-jdk21"
              tty: true
            retentionStrategy:
              idleMinutes: 10
            connector:
              attach:
                user: "jenkins"

          # --- Agente para Terraform (misma imagen base por simplicidad) ---
          - name: "terraform-agent"
            labelString: "terraform"
            remoteFs: "/home/jenkins"
            instanceCapStr: "5"
            dockerTemplateBase:
              image: "jenkins/inbound-agent:alpine-jdk21"
              tty: true
            retentionStrategy:
              idleMinutes: 10
            connector:
              attach:
                user: "jenkins"

          # --- Agente para Node (igual base) ---
          - name: "node-agent"
            labelString: "node"
            remoteFs: "/home/jenkins"
            instanceCapStr: "3"
            dockerTemplateBase:
              image: "jenkins/inbound-agent:alpine-jdk21"
              tty: true
            retentionStrategy:
              idleMinutes: 5
            connector:
              attach:
                user: "jenkins"

jobs:
  - script: >
      pipelineJob('infra-dind-job') {
        definition {
          cps {
            script("""
              pipeline {
                agent none

                stages {
                  stage('Probar agente Docker') {
                    agent { label 'docker' }
                    steps {
                      sh 'echo Hola desde el agente Docker'
                      sh 'hostname'
                    }
                  }

                  stage('Probar agente Terraform') {
                    agent { label 'terraform' }
                    steps {
                      sh 'echo Hola desde el agente Terraform'
                      sh 'hostname'
                    }
                  }

                  stage('Probar agente Node') {
                    agent { label 'node' }
                    steps {
                      sh 'echo Hola desde el agente Node'
                      sh 'hostname'
                    }
                  }
                }
              }
            """)
            sandbox()
          }
        }
      }
