jenkins:
  systemMessage: "Jenkins a medida para TimbaTumbao ✨"
  slaveAgentPort: 50000
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  clouds:
    - docker:
        name: "docker"
        dockerApi:
          dockerHost:
            uri: "tcp://dind:2375"
        templates:
          # === Agente Terraform AWSCLI Checkov ===
          - name: "terraform-agent"
            labelString: "terraform"
            remoteFs: "/home/jenkins"
            instanceCapStr: 3
            dockerTemplateBase:
              image: "custom-agent/terraform"
              tty: true
            retentionStrategy:
              idleMinutes: 5
            connector:
              attach:
                user: "jenkins"
          
          # === Agente NodeJS ===
          - name: "node-agent"
            labelString: "node"
            remoteFs: "/home/jenkins"
            instanceCapStr: 3
            dockerTemplateBase:
              image: "custom-agent/node"
              tty: true
            retentionStrategy:
              idleMinutes: 5
            connector:
              attach:
                user: "jenkins"

          # === Agente Maven (Java) ===
          - name: "maven-agent"
            labelString: "maven"
            remoteFs: "/home/jenkins"
            instanceCapStr: 2
            dockerTemplateBase:
              image: "custom-agent/maven"
              tty: true
            retentionStrategy:
              idleMinutes: 5
            connector:
              attach:
                user: "jenkins"
                
          # === Agente Docker CLI ===
          - name: "docker-agent"
            labelString: "docker"
            remoteFs: "/home/jenkins"
            instanceCapStr: 5
            dockerTemplateBase:
              image: "custom-agent/docker"
              tty: true
            retentionStrategy:
              idleMinutes: 10
            connector:
              attach:
                user: "jenkins"

unclassified:
  location:
    url: "http://jenkins-controller:8080/"

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "aws-credentials-00"
              username: "${AWS_ACCESS_KEY_ID}"
              password: "${AWS_SECRET_ACCESS_KEY}"

jobs:
  - script: >
      pipelineJob('timbatumbao-iac-pipeline') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/AndyFM806/TIMBATUMBAOINFRA.git')
                }
                branches('*/main')
              }
            }
            scriptPath('pipelines/Jenkinsfile')
          }
        }
      }

tool:
  jdk:
    installations:
      - name: 'jdk17'
        home: '/usr/lib/jvm/java-17-openjdk-amd64'
