jenkins:
  systemMessage: "Jenkins configurado automáticamente con JCasC"
  security:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
  clouds:
    - docker:
        name: "docker"
        dockerApi:
          dockerHost:
            uri: "unix:///var/run/docker.sock"
        templates:
          - labelString: "maven"
            connector:
              $class: "io.jenkins.docker.connector.DockerComputerAttachConnector"
              user: "root"
            dockerTemplateBase:
              image: "maven-agent"
            remoteFs: "/home/jenkins/agent"

          - labelString: "terraform"
            connector:
              $class: "io.jenkins.docker.connector.DockerComputerAttachConnector"
              user: "root"
            dockerTemplateBase:
              image: "terraform-agent"
            remoteFs: "/home/jenkins/agent"

jobs:
  - script: >
      pipelineJob('timbatumbao-ci-cd') {
        definition {
          cps {
            script(readFileFromWorkspace('pipelines/Jenkinsfile'))
            sandbox()
          }
        }
      }
