
jenkins:
  systemMessage: "Jenkins configurado automáticamente con JCasC"
  security:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
  clouds:
    - docker:
        $class: "com.nirima.jenkins.plugins.docker.DockerCloud"
        name: "docker"
        dockerApi:
          dockerHost:
            uri: "unix:///var/run/docker.sock"
        templates:
          - labelString: "maven"
            connector:
              $class: "io.jenkins.docker.connector.DockerComputerSSHConnector"
              sshKeyStrategy: "sshKeyPath"
            dockerTemplateBase:
              image: "maven:3.9-eclipse-temurin-17"
            remoteFs: "/home/jenkins/agent"
          - labelString: "terraform"
            connector:
              $class: "io.jenkins.docker.connector.DockerComputerSSHConnector"
              sshKeyStrategy: "sshKeyPath"
            dockerTemplateBase:
              image: "hashicorp/terraform:1.7"
            remoteFs: "/home/jenkins/agent"
jobs:
  - script: >
      pipelineJob('timbatumbao-ci-cd') {
        definition {
          cps {
            script(readFileFromWorkspace('pipelines/Jenkinsfile'))
            sandbox()
          }
        }
      }
