jenkins:
  systemMessage: "Jenkins configurado con acceso directo admin/admin"

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  disableRememberMe: false

  # AQUÃ van las nubes, DENTRO de 'jenkins'
  clouds:
    - docker:
        name: "dind-cloud"
        dockerApi:
          dockerHost:
            uri: "tcp://docker-dind:2375"
        templates:
          - name: "docker-agent"
            labelString: "docker"
            dockerTemplateBase:
              image: "jenkins/ssh-agent:jdk11"
            connector:
              attach:
                user: "jenkins"

          - name: "terraform-agent"
            labelString: "terraform"
            dockerTemplateBase:
              image: "jenkins/ssh-agent:jdk11"
            connector:
              attach:
                user: "jenkins"

jobs:
  - script: >
      pipelineJob('infra-dind-job') {
        definition {
          cps {
            script("""
              pipeline {
                agent none

                stages {
                  stage('Docker agent') {
                    agent { label 'docker' }
                    steps {
                      sh 'echo Hola desde el agente Docker'
                      sh 'hostname'
                    }
                  }

                  stage('Terraform agent') {
                    agent { label 'terraform' }
                    steps {
                      sh 'echo Hola desde el agente Terraform'
                      sh 'hostname'
                    }
                  }
                }
              }
            """)
            sandbox()
          }
        }
      }
